"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 3
final_space = true

[secondary_prompt]
  template = '> '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '$ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ if not .Detached }}{{ .HEAD }}{{else}}{{ printf "%.7s" .Commit.Sha }}{{end}}{{ if or .Working.Changed .Staging.Changed}}<yellow>*</>{{end}}{{ if .Commit.Refs.Tags }}  {{ join ",  " .Commit.Refs.Tags }}{{end}}{{ if gt .Ahead 0 }} <cyan>↑{{ .Ahead }}</>{{ end }}{{ if gt .Behind 0 }} <yellow>↓{{ .Behind }}</>{{ end }}{{ if gt .StashCount 0 }} <black>󱁐{{ .StashCount }}</>{{ end }}'
    foreground = 'white'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if .Detached }}magenta{{ else }}white{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      commit_icon = ''
      fetch_status = true
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '$'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
